platform :ios, '13'
use_frameworks!
inhibit_all_warnings!

target 'Example' do
  pod 'VVTools', :path => '../'
end

post_install do |installer|

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13'
    end
  end

end
